admin_homepage:
    path:     /
    defaults: { _controller: AdminBundle:Default:index }
    
admin_pais:
    resource: "@AdminBundle/Resources/config/routing/pais.yml"
    prefix:   /pais
    
admin_departamento:
    resource: "@AdminBundle/Resources/config/routing/departamento.yml"
    prefix:   /departamento
    
admin_menu:
    resource: "@AdminBundle/Resources/config/routing/menu.yml"
    prefix:   /menu 
    
admin_contabilidad:
    path:     /admin_contabilidad
    defaults: { _controller: AdminBundle:Contabilidad:index }

admin_contabilidad_buscar:
    path:     /admin_contabilidad_buscar
    defaults: { _controller: AdminBundle:Contabilidad:buscar }

admin_contabilidad_ver_pago:
    path:     /admin_contabilidad_ver_pago
    defaults: { _controller: AdminBundle:Contabilidad:verPago }
    methods:  [POST]

admin_contabilidad_procesar_pago:
    path:     /admin_contabilidad_procesar_pago
    defaults: { _controller: AdminBundle:Contabilidad:procesarPago }
    methods:  [POST]

admin_contabilidad_pagos_pendientes:
    path:     /admin_contabilidad_pagos_pendientes
    defaults: { _controller: AdminBundle:Contabilidad:pagosPendientes }

admin_contabilidad_reporte:
    path:     /admin_contabilidad_reporte
    defaults: { _controller: AdminBundle:ContabilidadReportes:index}

admin_contabilidad_reporte_ver:
    path:     /admin_contabilidad_reporte_ver
    defaults: { _controller: AdminBundle:ContabilidadReportes:ver }
    methods:  [POST]

admin_correos:
    path: /admin_correos
    defaults: { _controller: AdminBundle:Correos:index }