admin_homepage:
    path:     /
    defaults: { _controller: AdminBundle:Default:index }
    
admin_pais:
    resource: "@AdminBundle/Resources/config/routing/pais.yml"
    prefix:   /pais
    
admin_departamento:
    resource: "@AdminBundle/Resources/config/routing/departamento.yml"
    prefix:   /departamento
    
admin_menu:
    resource: "@AdminBundle/Resources/config/routing/menu.yml"
    prefix:   /menu 
    
admin_contabilidad:
    path:     /admin_contabilidad
    defaults: { _controller: AdminBundle:Contabilidad:index }

admin_contabilidad_buscar:
    path:     /admin_contabilidad_buscar
    defaults: { _controller: AdminBundle:Contabilidad:buscar }
