admin_homepage:
    path:     /
    defaults: { _controller: AdminBundle:Default:index }
    
admin_pais:
    resource: "@AdminBundle/Resources/config/routing/pais.yml"
    prefix:   /pais
    
admin_departamento:
    resource: "@AdminBundle/Resources/config/routing/departamento.yml"
    prefix:   /departamento
    
admin_menu:
    resource: "@AdminBundle/Resources/config/routing/menu.yml"
    prefix:   /menu 
    
admin_modulos:
    resource: "@AdminBundle/Resources/config/routing/modulos.yml"
    prefix:   /modulos

admin_secciones_modulos:
    resource: "@AdminBundle/Resources/config/routing/secciones_modulos.yml"
    prefix:   /secciones_modulos
    
admin_clientes_modulos:
    resource: "@AdminBundle/Resources/config/routing/clientes_modulos.yml"
    prefix:   /clientes_modulos
    
admin_campos_modulos:
    resource: "@AdminBundle/Resources/config/routing/campos_modulos.yml"
    prefix: /campos_modulos

admin_contabilidad:
    path:     /admin_contabilidad
    defaults: { _controller: AdminBundle:Contabilidad:index }

admin_contabilidad_buscar:
    path:     /admin_contabilidad_buscar
    defaults: { _controller: AdminBundle:Contabilidad:buscar }

admin_contabilidad_ver_pago:
    path:     /admin_contabilidad_ver_pago
    defaults: { _controller: AdminBundle:Contabilidad:verPago }
    methods:  [POST]

admin_contabilidad_procesar_pago:
    path:     /admin_contabilidad_procesar_pago
    defaults: { _controller: AdminBundle:Contabilidad:procesarPago }
    methods:  [POST]

admin_contabilidad_pagos_pendientes:
    path:     /admin_contabilidad_pagos_pendientes
    defaults: { _controller: AdminBundle:Contabilidad:pagosPendientes }

admin_contabilidad_reporte:
    path:     /admin_contabilidad_reporte
    defaults: { _controller: AdminBundle:ContabilidadReportes:index}

admin_contabilidad_reporte_ver:
    path:     /admin_contabilidad_reporte_ver
    defaults: { _controller: AdminBundle:ContabilidadReportes:ver }
    methods:  [POST]

admin_correos:
    path: /admin_correos
    defaults: { _controller: AdminBundle:Correos:index }
admin_correos_guardar:
    path: /admin_correos_guardar
    defaults: { _controller: AdminBundle:Correos:guardar }
admin_correos_cargar:
    path: /admin_correos_cargar
    defaults: { _controller: AdminBundle:Correos:cargar }
admin_correos_probar:
    path: /admin_correos_probar
    defaults: { _controller: AdminBundle:Correos:probar }
admin_correos_probar_enviar:
    path: /admin_correos_probar_enviar
    defaults: { _controller: AdminBundle:Correos:probarEnviar }

admin_contactanos:
        resource: "@AdminBundle/Resources/config/routing/contactanos.yml"
        prefix:   /contactanos
