<?php

namespace AppBundle\Repository;

/**
 * cliente_ajustesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class cliente_ajustesRepository extends \Doctrine\ORM\EntityRepository
{
}
