<?php

namespace AppBundle\Repository;

/**
 * ContactanosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactanosRepository extends \Doctrine\ORM\EntityRepository
{
}
