<?php

namespace AppBundle\Repository;

/**
 * PlantillaCorreoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlantillaCorreoRepository extends \Doctrine\ORM\EntityRepository
{
}
