<?php

namespace AppBundle\Repository;

/**
 * PlantillasCorreoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlantillasCorreoRepository extends \Doctrine\ORM\EntityRepository
{
}
