<?php

namespace AppBundle\Repository;

/**
 * SolicitudContactoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SolicitudContactoRepository extends \Doctrine\ORM\EntityRepository
{
}
