<?php

namespace AppBundle\Repository;

/**
 * TimezonesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TimezonesRepository extends \Doctrine\ORM\EntityRepository
{
}
