app:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /

# Rutas para los Doctores, Hospitales, Secretarias, etc.
emr:
    resource: "@EmrBundle/Resources/config/routing.yml"
    host:     "%emr_domain%"
    defaults:
        domain: '%emr_domain%'
    requirements:
        domain: '%emr_domain%'

# Rutas para manejo de cobros, ajustes del sistema, cambios de usuarios, etc.
admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    host:     "%admin_domain%"
    defaults:
        domain: '%admin_domain%'
    requirements:
        domain: '%admin_domain%'

# Sitio web publico
web:
    resource: "@WebBundle/Resources/config/routing.yml"
    prefix:   /