landing:
    resource: "@LandingBundle/Resources/config/routing.yml"
    prefix:   /

support:
    resource: "@SupportBundle/Resources/config/routing.yml"
    prefix:   /
    host:     "%emr_domain%"
    defaults:
        domain: '%emr_domain%'
    requirements:
        domain: '^%emr_domain%$'

# no tocar ni ponerle host
login:
    path:     /login
    defaults: { _controller: AppBundle:Security:login }
logout:
   path: /logout

login_api:
    path:     /api/login
    defaults: { _controller: AppBundle:Security:loginApi }

##########################

app:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /

# Rutas para los Doctores, Hospitales, Secretarias, etc.
emr:
    resource: "@EmrBundle/Resources/config/routing.yml"
    host:     "%emr_domain%"
    defaults:
        domain: '%emr_domain%'
    requirements:
        domain: '^%emr_domain%$'

# Rutas para manejo de cobros, ajustes del sistema, cambios de usuarios, etc.
admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    host:     "%admin_domain%"
    defaults:
        domain: '%admin_domain%'
    requirements:
        domain: '^%admin_domain%$'

# Sitio web publico
web:
    resource: "@WebBundle/Resources/config/routing.yml"
    prefix:   /
    host:     "%public_domain%"
    defaults:
        domain: '%public_domain%'
    requirements:
        domain: '^%public_domain%$'