# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        AppBundle\Entity\SysUsuario:
            algorithm: sha1
            encode_as_base64: false
            iterations: 1
    
    providers:
        doctrine_db_provider:
            entity:
                class: AppBundle:SysUsuario
                # property: usuario -- not used so it utilizes SysUsuarioRepository:loadUserByUsername

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            provider: doctrine_db_provider
            anonymous: ~
            logout:
                path: /logout
            form_login:
                use_referer: true
                login_path: login
                check_path: login

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_USER }