# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        AppBundle\Entity\Usuario:
            algorithm: sha1
            encode_as_base64: false
            iterations: 1
    
    providers:
        doctrine_db_provider:
            entity:
                class: AppBundle:Usuario
                property: usuUsuario

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            provider: doctrine_db_provider
            anonymous: ~
            logout:
                path: /logout
            form_login:
                use_referer: true
                login_path: login
                check_path: login
                always_use_default_target_path: true
                default_target_path:  /    
            logout:
                path: /logout
                target: /login    

        api:
            provider: doctrine_db_provider
            pattern: ^/api
            anonymous: ~
            form_login: false
            http_basic:
              realm: "REST Service Realm"

    access_control:
        - { path: ^/cliente/nuevo, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY,  host: '^%public_domain%$' }
        - { path: ^/, roles: ROLE_USER}
        
