# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    srv_parameters:
        class: AppBundle\Services\servicioParametros
        arguments: ["@doctrine.orm.entity_manager", "@logs"]

    srv_uploadFile:
        class:        Services\UploadFile
        arguments:     ["@doctrine.orm.entity_manager"]
        
    srv_session:
        class:        Services\ConfigureSession
        arguments:     ["@doctrine.orm.entity_manager", "@session"]    
        
    srv_catalogs:
        class:        Services\CatalogsService
        arguments:     [ "@doctrine.orm.entity_manager" ]
        arguments:     ["@doctrine.orm.entity_manager", "@session"]
        
    srv_patient:
        class:        Services\Patient
        arguments:     ["@doctrine.orm.entity_manager", "@session"] 

    srv_busqueda:
        class:        Services\Busqueda
        arguments:     ["@doctrine.orm.entity_manager", "@session", "@search.sphinxsearch.search"]

    srv_correos:
        class:        Services\Correos
        arguments:     ["@doctrine.orm.entity_manager", "@session", "@mailer"]
