sysarea_index:
    path:     /
    defaults: { _controller: "AppBundle:SysArea:index" }
    methods:  GET

sysarea_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:SysArea:show" }
    methods:  GET

sysarea_new:
    path:     /new
    defaults: { _controller: "AppBundle:SysArea:new" }
    methods:  [GET, POST]

sysarea_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:SysArea:edit" }
    methods:  [GET, POST]

sysarea_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:SysArea:delete" }
    methods:  DELETE
