sysantecedentesespecialidad_index:
    path:     /
    defaults: { _controller: "AppBundle:SysAntecedentesEspecialidad:index" }
    methods:  GET

sysantecedentesespecialidad_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:SysAntecedentesEspecialidad:show" }
    methods:  GET

sysantecedentesespecialidad_new:
    path:     /new
    defaults: { _controller: "AppBundle:SysAntecedentesEspecialidad:new" }
    methods:  [GET, POST]

sysantecedentesespecialidad_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:SysAntecedentesEspecialidad:edit" }
    methods:  [GET, POST]

sysantecedentesespecialidad_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:SysAntecedentesEspecialidad:delete" }
    methods:  DELETE
