sysdepartamentos_index:
    path:     /
    defaults: { _controller: "AppBundle:SysDepartamentos:index" }
    methods:  GET

sysdepartamentos_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:SysDepartamentos:show" }
    methods:  GET

sysdepartamentos_new:
    path:     /new
    defaults: { _controller: "AppBundle:SysDepartamentos:new" }
    methods:  [GET, POST]

sysdepartamentos_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:SysDepartamentos:edit" }
    methods:  [GET, POST]

sysdepartamentos_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:SysDepartamentos:delete" }
    methods:  DELETE
