sysespecialidades_index:
    path:     /
    defaults: { _controller: "AppBundle:SysEspecialidades:index" }
    methods:  GET

sysespecialidades_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:SysEspecialidades:show" }
    methods:  GET

sysespecialidades_new:
    path:     /new
    defaults: { _controller: "AppBundle:SysEspecialidades:new" }
    methods:  [GET, POST]

sysespecialidades_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:SysEspecialidades:edit" }
    methods:  [GET, POST]

sysespecialidades_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:SysEspecialidades:delete" }
    methods:  DELETE
