sysexamenesmedicos_index:
    path:     /
    defaults: { _controller: "AppBundle:SysExamenesMedicos:index" }
    methods:  GET

sysexamenesmedicos_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:SysExamenesMedicos:show" }
    methods:  GET

sysexamenesmedicos_new:
    path:     /new
    defaults: { _controller: "AppBundle:SysExamenesMedicos:new" }
    methods:  [GET, POST]

sysexamenesmedicos_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:SysExamenesMedicos:edit" }
    methods:  [GET, POST]

sysexamenesmedicos_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:SysExamenesMedicos:delete" }
    methods:  DELETE
