sysmodulos_index:
    path:     /
    defaults: { _controller: "AppBundle:SysModulos:index" }
    methods:  GET

sysmodulos_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:SysModulos:show" }
    methods:  GET

sysmodulos_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:SysModulos:edit" }
    methods:  [GET, POST]

sysmodulos_new:
    path:     /new
    defaults: { _controller: "AppBundle:SysModulos:new" }
    methods:  [GET, POST]

sysmodulos_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:SysModulos:delete" }
    methods:  DELETE


