sysmunicipio_index:
    path:     /
    defaults: { _controller: "AppBundle:SysMunicipio:index" }
    methods:  GET

sysmunicipio_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:SysMunicipio:show" }
    methods:  GET

sysmunicipio_new:
    path:     /new
    defaults: { _controller: "AppBundle:SysMunicipio:new" }
    methods:  [GET, POST]

sysmunicipio_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:SysMunicipio:edit" }
    methods:  [GET, POST]

sysmunicipio_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:SysMunicipio:delete" }
    methods:  DELETE
