syspais_index:
    path:     /
    defaults: { _controller: "AppBundle:SysPais:index" }
    methods:  GET

syspais_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:SysPais:show" }
    methods:  GET

syspais_new:
    path:     /new
    defaults: { _controller: "AppBundle:SysPais:new" }
    methods:  [GET, POST]

syspais_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:SysPais:edit" }
    methods:  [GET, POST]

syspais_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:SysPais:delete" }
    methods:  DELETE
