sys_pais_index:
    path:     /
    defaults: { _controller: "AppBundle:SysPais:index" }
    methods:  GET

sys_pais_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:SysPais:show" }
    methods:  GET

sys_pais_new:
    path:     /new
    defaults: { _controller: "AppBundle:SysPais:new" }
    methods:  [GET, POST]

sys_pais_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:SysPais:edit" }
    methods:  [GET, POST]

sys_pais_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:SysPais:delete" }
    methods:  DELETE
