sysperiodosmedico_index:
    path:     /
    defaults: { _controller: "AppBundle:SysPeriodosMedico:index" }
    methods:  GET

sysperiodosmedico_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:SysPeriodosMedico:show" }
    methods:  GET

sysperiodosmedico_new:
    path:     /new
    defaults: { _controller: "AppBundle:SysPeriodosMedico:new" }
    methods:  [GET, POST]

sysperiodosmedico_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:SysPeriodosMedico:edit" }
    methods:  [GET, POST]

sysperiodosmedico_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:SysPeriodosMedico:delete" }
    methods:  DELETE
