sysroles_index:
    path:     /
    defaults: { _controller: "AppBundle:SysRoles:index" }
    methods:  GET

sysroles_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:SysRoles:show" }
    methods:  GET

sysroles_new:
    path:     /new
    defaults: { _controller: "AppBundle:SysRoles:new" }
    methods:  [GET, POST]

sysroles_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:SysRoles:edit" }
    methods:  [GET, POST]

sysroles_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:SysRoles:delete" }
    methods:  DELETE
