syssugerencias_index:
    path:     /
    defaults: { _controller: "AppBundle:SysSugerencias:index" }
    methods:  GET

syssugerencias_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:SysSugerencias:show" }
    methods:  GET

syssugerencias_new:
    path:     /new
    defaults: { _controller: "AppBundle:SysSugerencias:new" }
    methods:  [GET, POST]

syssugerencias_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:SysSugerencias:edit" }
    methods:  [GET, POST]

syssugerencias_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:SysSugerencias:delete" }
    methods:  DELETE
