systipoinstitucion_index:
    path:     /
    defaults: { _controller: "AppBundle:SysTipoInstitucion:index" }
    methods:  GET

systipoinstitucion_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:SysTipoInstitucion:show" }
    methods:  GET

systipoinstitucion_new:
    path:     /new
    defaults: { _controller: "AppBundle:SysTipoInstitucion:new" }
    methods:  [GET, POST]

systipoinstitucion_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:SysTipoInstitucion:edit" }
    methods:  [GET, POST]

systipoinstitucion_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:SysTipoInstitucion:delete" }
    methods:  DELETE
