sysusuario_index:
    path:     /
    defaults: { _controller: "AppBundle:SysUsuario:index" }
    methods:  GET

sysusuario_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:SysUsuario:show" }
    methods:  GET

sysusuario_new:
    path:     /new
    defaults: { _controller: "AppBundle:SysUsuario:new" }
    methods:  [GET, POST]

sysusuario_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:SysUsuario:edit" }
    methods:  [GET, POST]

sysusuario_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:SysUsuario:delete" }
    methods:  DELETE
