pais_index:
    path:     /
    defaults: { _controller: "AdminBundle:Pais:index" }
    methods:  GET

pais_show:
    path:     /{id}/show
    defaults: { _controller: "AdminBundle:Pais:show" }
    methods:  GET

pais_new:
    path:     /new
    defaults: { _controller: "AdminBundle:Pais:new" }
    methods:  [GET, POST]

pais_edit:
    path:     /{id}/edit
    defaults: { _controller: "AdminBundle:Pais:edit" }
    methods:  [GET, POST]

pais_delete:
    path:     /{id}/delete
    defaults: { _controller: "AdminBundle:Pais:delete" }
    methods:  DELETE
    
pais_delete_from_list:
    path:     /list/delete/country
    defaults: { _controller: "AdminBundle:Pais:deleteCustom" }
