img_convertir:
    path:     /img/{ancho}/{alto}/{hash}.jpg
    defaults: { _controller: AppBundle:Image:index }
    methods: [GET]
    requirements:
      ancho: \d+
      alto: \d+
      hash: .{40}

ws_login:
    path: /ws/login
    defaults: { _controller: AppBundle:wsLogin:wsLogin }
    methods: [POST]