# no tocar ni ponerle host
login:
    path:     /login
    defaults: { _controller: AppBundle:Security:login }

#login_check:
    #path:   /login
    
logout:
    path:   /logout

   
app_syspais:
    resource: "@AppBundle/Resources/config/routing/syspais.yml"
    prefix:   /pais
    host:     "%admin_domain%"

