app_sysroles:
    resource: "@AppBundle/Resources/config/routing/sysroles.yml"
    prefix:   /sysroles
    
app_syspais:
    resource: "@AppBundle/Resources/config/routing/syspais.yml"
    prefix:   /syspais
    
app_sysdepartamentos:
    resource: "@AppBundle/Resources/config/routing/sysdepartamentos.yml"
    prefix:   /sysdepartamentos
    
app_sysmunicipio:
    resource: "@AppBundle/Resources/config/routing/sysmunicipio.yml"
    prefix:   /sysmunicipio
    
app_sysusuario:
    resource: "@AppBundle/Resources/config/routing/sysusuario.yml"
    prefix:   /sysusuario
    
app_systipoinstitucion:
    resource: "@AppBundle/Resources/config/routing/systipoinstitucion.yml"
    prefix:   /systipoinstitucion

app_sysmodulos:
        resource: "@AppBundle/Resources/config/routing/sysmodulos.yml"
        prefix:   /sysmodulos
        
app_sysarea:
        resource: "@AppBundle/Resources/config/routing/sysarea.yml"
        prefix:   /sysarea

app_sysespecialidades:
        resource: "@AppBundle/Resources/config/routing/sysespecialidades.yml"
        prefix:   /sysespecialidades

app_sysexamenesmedicos:
        resource: "@AppBundle/Resources/config/routing/sysexamenesmedicos.yml"
        prefix:   /sysexamenesmedicos

app_sysantecedentesespecialidad:
        resource: "@AppBundle/Resources/config/routing/sysantecedentesespecialidad.yml"
        prefix:   /sysantecedentesespecialidad

app_sysinstituciontienemodulo:
        resource: "@AppBundle/Resources/config/routing/sysinstituciontienemodulo.yml"
        prefix:   /sysinstituciontienemodulo


