services:
#    admin.example:
#        class: AdminBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
    parametros:
        class: AppBundle\Services\servicioParametros
        arguments: [ "@doctrine.orm.entity_manager", "@logs" ]
        
    logs:
        class: AppBundle\Services\servicioLogs
        arguments: [ "@doctrine.orm.entity_manager", "@security.token_storage", "@security.authorization_checker" ]
