services:
#    admin.example:
#        class: AdminBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
    parametros:
        class: AppBundle\Services\servicioParametros
        arguments: [ "@doctrine.orm.entity_manager" ]