services:
#    admin.example:
#        class: AdminBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
        
    logs:
        class: AppBundle\Services\servicioLogs
        arguments: [ "@doctrine.orm.entity_manager", "@security.token_storage", "@security.authorization_checker" ]
        
        
    #parametros:
    #    class: AppBundle\Services\servicioParametros
    #    arguments: [ "@doctrine.orm.entity_manager", "@logs" ]    

    seo:
      class: AppBundle\Twig\AppExtension
      tags:
        - { name: twig.extension }