cliente_index:
    path:     /
    defaults: { _controller: "EmrBundle:Cliente:index" }
    methods:  GET

cliente_show:
    path:     /{id}/info
    defaults: { _controller: "EmrBundle:Cliente:show" }
    methods:  GET

cliente_new:
    path:     /nuevo
    defaults: { _controller: "EmrBundle:Cliente:new" }
    methods:  [GET, POST]

cliente_edit:
    path:     /{id}/editar
    defaults: { _controller: "EmrBundle:Cliente:edit" }
    methods:  [GET, POST]

cliente_delete:
    path:     /{id}/eliminar
    defaults: { _controller: "EmrBundle:Cliente:delete" }
    methods:  DELETE

cliente_check_available_user:
    path:     /available/user
    defaults: { _controller: "EmrBundle:Cliente:checkAvailableUser" }
    
cliente_valid_form:
    path:     /valida/form
    defaults: { _controller: "EmrBundle:Cliente:validForm" }