cliente_index:
    path:     /
    defaults: { _controller: "EmrBundle:Cliente:index" }
    methods:  GET

cliente_show:
    path:     /{id}/show
    defaults: { _controller: "EmrBundle:Cliente:show" }
    methods:  GET

cliente_new:
    path:     /new
    defaults: { _controller: "EmrBundle:Cliente:new" }
    methods:  [GET, POST]

cliente_edit:
    path:     /{id}/edit
    defaults: { _controller: "EmrBundle:Cliente:edit" }
    methods:  [GET, POST]

cliente_delete:
    path:     /{id}/delete
    defaults: { _controller: "EmrBundle:Cliente:delete" }
    methods:  DELETE

cliente_check_available_user:
    path:     /available/user
    defaults: { _controller: "EmrBundle:Cliente:checkAvailableUser" }