consulta_index:
    path:     /
    defaults: { _controller: "EmrBundle:Consulta:index" }
    #methods:  GET

consulta_show:
    path:     /{id}/info
    defaults: { _controller: "EmrBundle:Consulta:show" }
    #methods:  GET

consulta_new:
    path:     /medica/{id}/{cm}
    defaults: { _controller: "EmrBundle:Consulta:medicalConsultation" }
    #methods:  [GET, POST]
    
consulta_procesa:
    path:     /procesa/consulta
    defaults: { _controller: "EmrBundle:Consulta:processAppointment" } 
    
consulta_estado_cita:
    path:     /proceso/actual
    defaults: { _controller: "EmrBundle:Consulta:isRunningAppointment" } 
    
consulta_info_patient:
    path:     /info/patient/{id}
    defaults: { _controller: "EmrBundle:Consulta:getFullInfoPatient" }
    
consulta_set_prescription:
    path:     /prescription/patient
    defaults: { _controller: "EmrBundle:Consulta:setPrescription"}
    
consulta_print_prescription:
    path:     /prescription/print
    defaults: { _controller: "EmrBundle:Consulta:printPrescription"}
    
consulta_prescription_send_email:
    path:     /prescription/sendmail
    defaults: { _controller: "EmrBundle:Consulta:sendEmailPrescription"}
#agenda_edit:
    #path:     /{id}/editar
    #defaults: { _controller: "EmrBundle:Agenda:edit" }
    #methods:  [GET, POST]

#agenda_delete:
    #path:     /{id}/eliminar
    #defaults: { _controller: "EmrBundle:Agenda:delete" }
    #methods:  DELETE
