paciente_index:
    path:     /
    defaults: { _controller: "EmrBundle:Paciente:index" }
    methods:  GET

paciente_show:
    path:     /{id}/show
    defaults: { _controller: "EmrBundle:Paciente:show" }
    methods:  GET

paciente_new:
    path:     /new
    defaults: { _controller: "EmrBundle:Paciente:new" }
    methods:  [GET, POST]

paciente_edit:
    path:     /{id}/edit
    defaults: { _controller: "EmrBundle:Paciente:edit" }
    methods:  [GET, POST]

paciente_delete:
    path:     /{id}/delete
    defaults: { _controller: "EmrBundle:Paciente:delete" }
    methods:  DELETE
    
    
paciente_form:
    path:     /form/paciente
    defaults: { _controller: "EmrBundle:Paciente:formPacientes" }
    
paciente_search:
    path:     /search/patients
    defaults: { _controller: "EmrBundle:Paciente:searchPatients" }
        
