AppBundle\Entity\Cita:
    type: entity
    table: cita
    indexes:
        FK_cit_paciente_idx:
            columns:
                - cit_pac_id
        FK_cit_cliente_idx:
            columns:
                - cit_cli_id
        FK_cit_usuarios_idx:
            columns:
                - cit_usu_id
    id:
        citId:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            column: cit_id
            generator:
                strategy: IDENTITY
    fields:
        #citFechaCita:
        #    type: date
        #    nullable: false
        #    column: cit_fecha_cita
        #citHoraInicioCita:
        #    type: datetime
        #    nullable: false
        #    column: cit_hora_inicio_cita
        #citHoraFinCita:
        #    type: datetime
        #    nullable: false
        #    column: cit_hora_fin_cita    
        citSala:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
            column: cit_sala
        citNotas:
            type: string
            nullable: true
            length: 500
            options:
                fixed: false
            column: cit_notas
        citFechaCrea:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
            column: cit_fecha_crea
        citFechaMod:
            type: datetime
            nullable: true
            column: cit_fecha_mod
        citActivo:
            type: boolean
            nullable: false
            options:
                default: '1'
            column: cit_activo
    manyToOne:
        citPac:
            targetEntity: Paciente
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                cit_pac_id:
                    referencedColumnName: pac_id
            orphanRemoval: false
        citCli:
            targetEntity: Cliente
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                cit_cli_id:
                    referencedColumnName: cli_id
            orphanRemoval: false
        citUsu:
            targetEntity: Usuario
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                cit_usu_id:
                    referencedColumnName: usu_id
            orphanRemoval: false
    lifecycleCallbacks: {  }
