AppBundle\Entity\Ciudad:
    type: entity
    table: ciudad
    indexes:
        FK_ciu_municipip_idx:
            columns:
                - ciu_mun_id
    id:
        ciuId:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            column: ciu_id
            generator:
                strategy: IDENTITY
    fields:
        ciuNombre:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
            column: ciu_nombre
        ciuFechaCrea:
            type: datetime
            nullable: true
            options:
                default: CURRENT_TIMESTAMP
            column: ciu_fecha_crea
        ciuFechaMod:
            type: datetime
            nullable: true
            column: ciu_fecha_mod
        ciuActivo:
            type: boolean
            nullable: true
            options:
                default: '1'
            column: ciu_activo
    manyToOne:
        ciuMun:
            targetEntity: Municipio
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                ciu_mun_id:
                    referencedColumnName: mun_id
            orphanRemoval: false
    lifecycleCallbacks: {  }
