AppBundle\Entity\Cliente:
    type: entity
    table: cliente
    indexes:
        IDX_cli_nit:
            columns:
                - cli_nit
        IDX_cli_nombre_fiscal:
            columns:
                - cli_nombre_fiscal
        FK_cli_tipo_cliente_idx:
            columns:
                - cli_tip_cli_id
        FK_cli_mun_idx:
            columns:
                - cli_mun_id
        IDX_F41C9B25575C5877:
            columns:
                - cli_metodo_pago_id
    id:
        cliId:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            column: cli_id
            generator:
                strategy: IDENTITY
    fields:
        cliNombre:
            type: string
            nullable: true
            length: 25
            options:
                fixed: false
            column: cli_nombre
        cliNombreFiscal:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
            column: cli_nombre_fiscal
        cliNit:
            type: string
            nullable: false
            length: 20
            options:
                fixed: false
            column: cli_nit
        cliTelefono1:
            type: string
            nullable: false
            length: 9
            options:
                fixed: false
            column: cli_telefono1
        cliTelefono2:
            type: string
            nullable: true
            length: 9
            options:
                fixed: false
            column: cli_telefono2
        cliDireccion:
            type: string
            nullable: false
            length: 150
            options:
                fixed: false
            column: cli_direccion
        cliFechaRegistro:
            type: date
            nullable: false
            column: cli_fecha_registro
        cliIdVendedor:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: cli_id_vendedor
        cliFechaCrea:
            type: datetime
            nullable: true
            column: cli_fecha_crea
        cliFechaMod:
            type: datetime
            nullable: true
            column: cli_fecha_mod
        cliActivo:
            type: boolean
            nullable: true
            options:
                default: '1'
            column: cli_activo
        cliNombreComercial:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: cli_nombre_comercial
        cliPagoDetalle:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: cli_pago_detalle
        cliPrecioPorUsuario:
            type: decimal
            nullable: true
            precision: 5
            scale: 2
            column: cli_precio_por_usuario
        cliUbicacionLat:
            type: string
            nullable: true
            length: 30
            options:
                fixed: false
            column: cli_ubicacion_lat
        cliUbicacionLon:
            type: string
            nullable: true
            length: 30
            options:
                fixed: false
            column: cli_ubicacion_lon
    manyToOne:
        cliMetodoPago:
            targetEntity: MetodoPago
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                cli_metodo_pago_id:
                    referencedColumnName: mep_id
            orphanRemoval: false
        cliTipCli:
            targetEntity: TipoCliente
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                cli_tip_cli_id:
                    referencedColumnName: tip_cli_id
            orphanRemoval: false
        cliMun:
            targetEntity: Municipio
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                cli_mun_id:
                    referencedColumnName: mun_id
            orphanRemoval: false
    manyToMany:
        idEspecialidad:
            targetEntity: Especialidad
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: idCliente
            joinTable:
                name: cliente_especialidad
                joinColumns:
                    -
                        name: id_cliente
                        referencedColumnName: cli_id
                inverseJoinColumns:
                    -
                        name: id_especialidad
                        referencedColumnName: esp_id
            orderBy: null
    lifecycleCallbacks: {  }
