AppBundle\Entity\ClienteUsuario:
    type: entity
    table: cliente_usuario
    indexes:
        FK_cliente_idx:
            columns:
                - cli_usu_cli_id
        FK_usuario_idx:
            columns:
                - cli_usu_usu_id
    id:
        cliUsuId:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            column: cli_usu_id
            generator:
                strategy: IDENTITY
    fields:
        cliUsuFechaCrea:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
            column: cli_usu_fecha_crea
        cliUsuFechaMod:
            type: datetime
            nullable: true
            column: cli_usu_fecha_mod
        cliUsuActivo:
            type: boolean
            nullable: false
            options:
                default: '1'
            column: cli_usu_activo
    uniqueConstraints:
        unique_idx:
          columns: [ cli_usu_usu_id, cli_usu_cli_id, cli_usu_rol_id ]
    manyToOne:
        cliUsuUsu:
            targetEntity: Usuario
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                cli_usu_usu_id:
                    referencedColumnName: usu_id
            orphanRemoval: false
        cliUsuCli:
            targetEntity: Cliente
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                cli_usu_cli_id:
                    referencedColumnName: cli_id
            orphanRemoval: false
        cliUsuRol:
            targetEntity: Rol
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                cli_usu_rol_id:
                    referencedColumnName: rol_id
            orphanRemoval: false
    lifecycleCallbacks: {  }
