AppBundle\Entity\Contactanos:
    type: entity
    table: contactanos
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        conNombre:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: con_nombre
        conEmail:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: con_email
        conTipo:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
            column: con_tipo
        conIp:
            type: string
            nullable: true
            length: 20
            options:
                fixed: false
            column: con_ip
        conMensaje:
            type: text
            nullable: true
            length: null
            options:
                fixed: false
            column: con_mensaje
        conFechaCrea:
            type: datetime
            nullable: true
            column: con_fecha_crea
        conActivo:
            type: boolean
            nullable: false
            options:
                default: '1'
            column: con_activo
    lifecycleCallbacks: {  }
