AppBundle\Entity\EavModSecGrupo:
    type: entity
    table: eav_mod_sec_grupo
    indexes:
        IDX_6B3087616A331933:
            columns:
                - sec_gr_secc_id
    id:
        secGrId:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            column: sec_gr_id
            generator:
                strategy: IDENTITY
    fields:
        secGrGrupo:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: sec_gr_grupo
        secGrActivo:
            type: boolean
            nullable: false
            options:
                default: '1'
            column: sec_gr_activo
        secGrFechaCrea:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
            column: sec_gr_fecha_crea
        secGrFechaMod:
            type: datetime
            nullable: true
            column: sec_gr_fecha_mod
        secGrOrden:
            type: integer
            nullable: false
            options:
                unsigned: true
            column: sec_gr_orden
    manyToOne:
        secGrSecc:
            targetEntity: EavModSeccion
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                sec_gr_secc_id:
                    referencedColumnName: mod_secc_id
            orphanRemoval: false
    lifecycleCallbacks: {  }
