AppBundle\Entity\EavModCampos:
    type: entity
    table: eav_mod_campos
    indexes:
        IDX_9088536D2788F83D:
            columns:
                - mod_camp_mod_secc_id
        FK_campos_tipcampos_idx:
            columns:
                - mod_camp_tip_camp_id
        IDX_9088536D991B23FC:
            columns:
                - mod_camp_campo_padre
    id:
        modCampId:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            column: mod_camp_id
            generator:
                strategy: IDENTITY
    fields:
        modCampNombre:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
            column: mod_camp_nombre
        modCampNombreCorto:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: mod_camp_nombre_corto
        modCampShowIfnull:
            type: boolean
            nullable: false
            options:
                default: '0'
            column: mod_camp_show_ifnull
        modCampValorDefault:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: mod_camp_valor_default
        modCampRequerido:
            type: boolean
            nullable: false
            options:
                default: '0'
            column: mod_camp_requerido
        modCampOrden:
            type: integer
            nullable: true
            options:
                unsigned: true
            column: mod_camp_orden
        modCampActivo:
            type: boolean
            nullable: false
            options:
                default: '1'
            column: mod_camp_activo
        modCampFechaCrea:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
            column: mod_camp_fecha_crea
        modCampFechaMod:
            type: datetime
            nullable: true
            column: mod_camp_fecha_mod
        modCampEsCatalogo:
            type: boolean
            nullable: true
            options:
                default: '0'
            column: mod_camp_es_catalogo
    manyToOne:
        modCampModSecc:
            targetEntity: EavModSeccion
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                mod_camp_mod_secc_id:
                    referencedColumnName: mod_secc_id
            orphanRemoval: false
        modCampCampoPadre:
            targetEntity: EavModCampos
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                mod_camp_campo_padre:
                    referencedColumnName: mod_camp_id
            orphanRemoval: false
        modCampTipCamp:
            targetEntity: EavTipCampos
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                mod_camp_tip_camp_id:
                    referencedColumnName: tip_camp_id
            orphanRemoval: false
    lifecycleCallbacks: {  }
