AppBundle\Entity\EavModSeccion:
    type: entity
    table: eav_mod_seccion
    indexes:
        FK_modulo_modseccion_idx:
            columns:
                - mod_secc_mod_id
    id:
        modSeccId:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            column: mod_secc_id
            generator:
                strategy: IDENTITY
    fields:
        modSeccSeccion:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
            column: mod_secc_seccion
        modSeccOrden:
            type: integer
            nullable: true
            options:
                unsigned: true
            column: mod_secc_orden
        modSeccActivo:
            type: boolean
            nullable: false
            options:
                default: '1'
            column: mod_secc_activo
        modSeccFechaCrea:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
            column: mod_secc_fecha_crea
        modSeccFechaMod:
            type: datetime
            nullable: true
            column: mod_secc_fecha_mod
    manyToOne:
        modSeccMod:
            targetEntity: Modulo
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                mod_secc_mod_id:
                    referencedColumnName: mod_id
            orphanRemoval: false
    lifecycleCallbacks: {  }
