AppBundle\Entity\EavModCatValores:
    type: entity
    table: eav_mod_cat_valores
    indexes:
        IDX_C546A49153FE0380:
            columns:
                - mod_cat_val_camp_id
    id:
        modCatValId:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            column: mod_cat_val_id
            generator:
                strategy: IDENTITY
    fields:
        modCatValValor:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: mod_cat_val_valor
        modCatValCatValPadre:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: mod_cat_val_cat_val_padre
        modCatValActivo:
            type: boolean
            nullable: false
            options:
                default: '1'
            column: mod_cat_val_activo
        modCatValFechaCrea:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
            column: mod_cat_val_fecha_crea
        modCatValFechaMod:
            type: datetime
            nullable: true
            column: mod_cat_val_fecha_mod
    manyToOne:
        modCatValCamp:
            targetEntity: EavModCampos
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                mod_cat_val_camp_id:
                    referencedColumnName: mod_camp_id
            orphanRemoval: false
    lifecycleCallbacks: {  }
