AppBundle\Entity\EavModDatos:
    type: entity
    table: eav_mod_datos
    indexes:
        IDX_40A89A644DE28A73:
            columns:
                - mod_dat_usu_id
        IDX_40A89A64727DD761:
            columns:
                - mod_dat_pac_id
        IDX_40A89A6460128381:
            columns:
                - mod_dat_cli_id
        IDX_40A89A64A8183B3:
            columns:
                - mod_dat_cit_id
        IDX_40A89A64E039DDBE:
            columns:
                - mod_dat_mod_camp_id
    id:
        modDatId:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            column: mod_dat_id
            generator:
                strategy: IDENTITY
    fields:
        modDatDatoValor:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: mod_dat_dato_valor
        modDatActivo:
            type: boolean
            nullable: false
            options:
                default: '1'
            column: mod_dat_activo
        modDatFechaCrea:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
            column: mod_dat_fecha_crea
        modDatFechaMod:
            type: datetime
            nullable: true
            column: mod_dat_fecha_mod
    manyToOne:
        modDatUsu:
            targetEntity: Usuario
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                mod_dat_usu_id:
                    referencedColumnName: usu_id
            orphanRemoval: false
        modDatCli:
            targetEntity: Cliente
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                mod_dat_cli_id:
                    referencedColumnName: cli_id
            orphanRemoval: false
        modDatPac:
            targetEntity: Paciente
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                mod_dat_pac_id:
                    referencedColumnName: pac_id
            orphanRemoval: false
        modDatCit:
            targetEntity: Cita
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                mod_dat_cit_id:
                    referencedColumnName: cit_id
            orphanRemoval: false
        modDatModCamp:
            targetEntity: EavModCampos
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                mod_dat_mod_camp_id:
                    referencedColumnName: mod_camp_id
            orphanRemoval: false
    lifecycleCallbacks: {  }
