AppBundle\Entity\Especialidad:
    type: entity
    table: especialidad
    id:
        espId:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            column: esp_id
            generator:
                strategy: IDENTITY
    fields:
        espEspecialidad:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
            column: esp_especialidad
        espCodigo:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
            column: esp_codigo
        espDescripcion:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: esp_descripcion
        espFechaCrea:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
            column: esp_fecha_crea
        espFechaMod:
            type: datetime
            nullable: true
            column: esp_fecha_mod
        espActivo:
            type: boolean
            nullable: false
            options:
                default: '1'
            column: esp_activo
    lifecycleCallbacks: {  }
