AppBundle\Entity\HistorialPago:
    type: entity
    table: historial_pago
    indexes:
        FK_mep_usuario_idx1:
            columns:
                - hpa_usu_id_verificado
        FK_hpa_metodo_pago_idx:
            columns:
                - hpa_mep_id
        FK_hpa_usuario_paga_idx:
            columns:
                - hpa_usu_id
    id:
        hpaId:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            column: hpa_id
            generator:
                strategy: IDENTITY
    fields:
        hpaMonto:
            type: decimal
            nullable: false
            precision: 5
            scale: 2
            column: hpa_monto
        hpaFechaPago:
            type: datetime
            nullable: false
            column: hpa_fecha_pago
        hpaVerificado:
            type: boolean
            nullable: true
            column: hpa_verificado
        hpaFechaCrea:
            type: datetime
            nullable: true
            options:
                default: CURRENT_TIMESTAMP
            column: hpa_fecha_crea
        hpaFechaMod:
            type: datetime
            nullable: true
            column: hpa_fecha_mod
        hpaActivo:
            type: boolean
            nullable: false
            options:
                default: '1'
            column: hpa_activo
    manyToOne:
        hpaMep:
            targetEntity: MetodoPago
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                hpa_mep_id:
                    referencedColumnName: mep_id
            orphanRemoval: false
        hpaUsu:
            targetEntity: Usuario
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                hpa_usu_id:
                    referencedColumnName: usu_id
            orphanRemoval: false
        hpaUsuVerificado:
            targetEntity: Usuario
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                hpa_usu_id_verificado:
                    referencedColumnName: usu_id
            orphanRemoval: false
    lifecycleCallbacks: {  }
