AppBundle\Entity\HistorialPago:
    type: entity
    table: historial_pago
    indexes:
        FK_mep_usuario_idx:
            columns:
                - hpa_usu_id_verificado
        FK_hpa_metodo_pago_idx:
            columns:
                - hpa_mep_id
        FK_hpa_cliente_paga_idx:
            columns:
                - hpa_cli_id
    id:
        hpaId:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            column: hpa_id
            generator:
                strategy: IDENTITY
    fields:
        hpaMontoEsperado:
            type: decimal
            nullable: false
            precision: 5
            scale: 2
            column: hpa_monto_esperado
        hpaMontoPagado:
            type: decimal
            nullable: false
            precision: 5
            scale: 2
            column: hpa_monto_pagado
        hpaFechaPago:
            type: datetime
            nullable: true
            column: hpa_fecha_pago
        hpaFechaCrea:
            type: datetime
            nullable: true
            options:
                default: CURRENT_TIMESTAMP
            column: hpa_fecha_crea
        hpaFechaMod:
            type: datetime
            nullable: true
            column: hpa_fecha_mod
        hpaComentario:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: hpa_comentario
        hpaCantidadUsuariosCorte:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: hpa_cantidad_usuarios_corte
        hpaEstado:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: hpa_estado
    manyToOne:
        hpaCli:
            targetEntity: Cliente
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                hpa_cli_id:
                    referencedColumnName: cli_id
            orphanRemoval: false
        hpaUsuVerificado:
            targetEntity: Usuario
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                hpa_usu_id_verificado:
                    referencedColumnName: usu_id
            orphanRemoval: false
        hpaMep:
            targetEntity: MetodoPago
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                hpa_mep_id:
                    referencedColumnName: mep_id
            orphanRemoval: false
    lifecycleCallbacks: {  }
