AppBundle\Entity\InvArea:
    type: entity
    table: inv_area
    indexes:
        FK_inv_area_cliente:
            columns:
                - iar_cli_id
    id:
        iarId:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            column: iar_id
            generator:
                strategy: IDENTITY
    fields:
        iarArea:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
            column: iar_area
        iarFechaCrea:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
            column: iar_fecha_crea
        iarFechaMod:
            type: datetime
            nullable: true
            column: iar_fecha_mod
        iarActivo:
            type: boolean
            nullable: false
            options:
                default: '1'
            column: iar_activo
    manyToOne:
        iarCli:
            targetEntity: Cliente
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                iar_cli_id:
                    referencedColumnName: cli_id
            orphanRemoval: false
    lifecycleCallbacks: {  }
