AppBundle\Entity\InvCategoria:
    type: entity
    table: inv_categoria
    indexes:
        FK_inv_categoria_cliente:
            columns:
                - ica_cli_id
    id:
        icaId:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            column: ica_id
            generator:
                strategy: IDENTITY
    fields:
        icaCategoria:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
            column: ica_categoria
        icaDescripcion:
            type: string
            nullable: true
            length: 150
            options:
                fixed: false
            column: ica_descripcion
        icaFechaCrea:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
            column: ica_fecha_crea
        icaFechaMod:
            type: datetime
            nullable: true
            column: ica_fecha_mod
        icaActivo:
            type: boolean
            nullable: false
            options:
                default: '1'
            column: ica_activo
    manyToOne:
        icaCli:
            targetEntity: Cliente
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                ica_cli_id:
                    referencedColumnName: cli_id
            orphanRemoval: false
    lifecycleCallbacks: {  }
