AppBundle\Entity\InvCategoria:
    type: entity
    table: inv_categoria
    id:
        icaId:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            column: ica_id
            generator:
                strategy: IDENTITY
    fields:
        icaCategoria:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
            column: ica_categoria
        icaDescripcion:
            type: string
            nullable: true
            length: 150
            options:
                fixed: false
            column: ica_descripcion
        icaFechaCrea:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
            column: ica_fecha_crea
        icaFechaMod:
            type: datetime
            nullable: true
            column: ica_fecha_mod
        icaActivo:
            type: boolean
            nullable: false
            options:
                default: '1'
            column: ica_activo
    lifecycleCallbacks: {  }
