AppBundle\Entity\InvTipoProveedor:
    type: entity
    table: inv_tipo_proveedor
    indexes:
        IDX_39E1E37D797BB3C6:
            columns:
                - itpr_cli_id
    id:
        itprId:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            column: itpr_id
            generator:
                strategy: IDENTITY
    fields:
        itprTipo:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
            column: itpr_tipo
        itprDescripcion:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: itpr_descripcion
        itprFechaCrea:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
            column: itpr_fecha_crea
        itprFechaMod:
            type: datetime
            nullable: true
            column: itpr_fecha_mod
        itprActivo:
            type: boolean
            nullable: false
            options:
                default: '1'
            column: itpr_activo
    manyToOne:
        itprCli:
            targetEntity: Cliente
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                itpr_cli_id:
                    referencedColumnName: cli_id
            orphanRemoval: false
    lifecycleCallbacks: {  }
