AppBundle\Entity\MenRol:
    type: entity
    table: men_rol
    id:
        mrolId:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            column: mrol_id
            generator:
                strategy: IDENTITY
    fields:
        mrolRol:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
            column: mrol_rol
        mrolFechaCrea:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
            column: mrol_fecha_crea
        mrolFechaMod:
            type: datetime
            nullable: true
            column: mrol_fecha_mod
        mrolActivo:
            type: boolean
            nullable: false
            options:
                default: '1'
            column: mrol_activo
    lifecycleCallbacks: {  }
