AppBundle\Entity\Parametros:
    type: entity
    table: parametros
    indexes:
        idx_par_llave:
            columns:
                - par_llave
    id:
        parId:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            column: par_id
            generator:
                strategy: IDENTITY
    fields:
        parLlave:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: par_llave
        parValor:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: par_valor
        parFechaMod:
            type: datetime
            nullable: true
            options:
                default: CURRENT_TIMESTAMP
            column: par_fecha_mod