AppBundle\Entity\Rol:
    type: entity
    table: rol
    id:
        rolId:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            column: rol_id
            generator:
                strategy: IDENTITY
    fields:
        rolRol:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
            column: rol_rol
        rolFechaCrea:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
            column: rol_fecha_crea
        rolFechaMod:
            type: datetime
            nullable: true
            column: rol_fecha_mod
        rolActivo:
            type: boolean
            nullable: false
            options:
                default: '1'
            column: rol_activo
    lifecycleCallbacks: {  }
