AppBundle\Entity\SocialRedes:
    type: entity
    table: social_redes
    id:
        idSocRed:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            column: id_soc_red
            generator:
                strategy: IDENTITY
    fields:
        socRedNombre:
            type: string
            nullable: false
            length: 250
            options:
                fixed: false
                default: '0'
            column: soc_red_nombre
        socPatron:
            type: string
            nullable: false
            length: 250
            options:
                fixed: false
                default: '0'
            column: soc_patron
        socRedActivo:
            type: boolean
            nullable: false
            options:
                default: '0'
            column: soc_red_activo
    lifecycleCallbacks: {  }
