AppBundle\Entity\SolicitudContacto:
    type: entity
    table: solicitud_contacto
    indexes:
        IDX_BDDA6CF9A95296AB:
            columns:
                - sc_cli_id
        IDX_BDDA6CF984A29F59:
            columns:
                - sc_usu_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        ip:
            type: string
            nullable: false
            length: 16
            options:
                fixed: false
        telefono:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        correo:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
        fechaContacto:
            type: datetime
            nullable: false
            column: fecha_contacto
        comentario:
            type: text
            nullable: false
            length: null
            options:
                fixed: false
        estado:
            type: integer
            nullable: false
            options:
                unsigned: false
        scNombre:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: sc_nombre
    manyToOne:
        scUsu:
            targetEntity: Usuario
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                sc_usu_id:
                    referencedColumnName: usu_id
            orphanRemoval: false
        scCli:
            targetEntity: Cliente
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                sc_cli_id:
                    referencedColumnName: cli_id
            orphanRemoval: false
    lifecycleCallbacks: {  }
