AppBundle\Entity\SoporteEstados:
    type: entity
    table: soporte_estados
    indexes:
        activo:
            columns:
                - activo
        cierre:
            columns:
                - cierre
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        estado:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        cierre:
            type: boolean
            nullable: false
        activo:
            type: boolean
            nullable: false
    lifecycleCallbacks: {  }
