AppBundle\Entity\SoporteMensajes:
    type: entity
    table: soporte_mensajes
    indexes:
        activo:
            columns:
                - activo
        tipo:
            columns:
                - tipo
        FK_soporte_mensajes_usuario:
            columns:
                - usuario_soporte_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        mensaje:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
        fecha:
            type: datetime
            nullable: false
        activo:
            type: integer
            nullable: false
            options:
                unsigned: true
                default: '0'
        tipo:
            type: integer
            nullable: false
            options:
                unsigned: true
                default: '0'
    manyToOne:
        usuarioSoporte:
            targetEntity: Usuario
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                usuario_soporte_id:
                    referencedColumnName: usu_id
            orphanRemoval: false
    lifecycleCallbacks: {  }
