AppBundle\Entity\SysArea:
    type: entity
    table: sys_area
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombreSysArea:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
            column: nombre_sys_area
        descripcionSysArea:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
            column: descripcion_sys_area
        estatusSysArea:
            type: boolean
            nullable: true
            column: estatus_sys_area
        nombreCortoSysArea:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
            column: nombre_corto_sys_area
        fechaCreacion:
            type: datetime
            nullable: true
            column: fecha_creacion
    lifecycleCallbacks: {  }
