AppBundle\Entity\SysAntecedentesEspecialidad:
    type: entity
    table: sys_antecedentes_especialidad
    indexes:
        FK_sys_antecedentes_especialidad_sys_especialidades:
            columns:
                - id_especialidad
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        antecedente:
            type: string
            nullable: true
            length: 200
            options:
                fixed: false
        valor:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
        descripcion:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
        fechaCreacion:
            type: datetime
            nullable: true
            column: fecha_creacion
    manyToOne:
        idEspecialidad:
            targetEntity: SysEspecialidades
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_especialidad:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
