AppBundle\Entity\SysAntecedetenUsuario:
    type: entity
    table: sys_antecedeten_usuario
    indexes:
        FK_sys_antecedeten_usuario_sys_antecedentes_especialidad:
            columns:
                - id_antecedente_especialidad
        FK_sys_antecedeten_usuario_sys_usuario:
            columns:
                - id_usuario
        FK_sys_antecedeten_usuario_sys_cita:
            columns:
                - id_cita
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        descripcion:
            type: integer
            nullable: true
            options:
                unsigned: false
        fechaCreacion:
            type: date
            nullable: true
            column: fecha_creacion
    manyToOne:
        idCita:
            targetEntity: SysCita
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_cita:
                    referencedColumnName: id
            orphanRemoval: false
        idAntecedenteEspecialidad:
            targetEntity: SysAntecedentesEspecialidad
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_antecedente_especialidad:
                    referencedColumnName: id
            orphanRemoval: false
        idUsuario:
            targetEntity: SysUsuario
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_usuario:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
