AppBundle\Entity\SysEspecialidades:
    type: entity
    table: sys_especialidades
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        categoriaSysEspecialidad:
            type: string
            nullable: true
            length: 60
            options:
                fixed: false
            column: categoria_sys_especialidad
        nombreSysEspecialidades:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: nombre_sys_especialidades
        descripcionSysEspecialidades:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: descripcion_sys_especialidades
        codigoSysEspecialidades:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: codigo_sys_especialidades
        estatusSysEspecialidad:
            type: boolean
            nullable: true
            column: estatus_sys_especialidad
    lifecycleCallbacks: {  }
