AppBundle\Entity\SysExamenesCitaMedica:
    type: entity
    table: sys_examenes_cita_medica
    indexes:
        FK_sys_examenes_cita_medica_sys_cita:
            columns:
                - id_cita
        FK_sys_examenes_cita_medica_sys_examenes_cita_medica:
            columns:
                - id_examen_medico
    uniqueConstraints:
        UNIQ_B376E27BB6AA104B:
            columns:
                - id_examen_medico
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        date:
            type: date
            nullable: true
        estatus:
            type: boolean
            nullable: true
            options:
                comment: '1 = Pendiente, 2 = Entregado'
    manyToOne:
        idCita:
            targetEntity: SysCita
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_cita:
                    referencedColumnName: id
            orphanRemoval: false
        idExamenMedico:
            targetEntity: SysExamenesCitaMedica
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_examen_medico:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
