AppBundle\Entity\SysEspecialidades:
    type: entity
    table: sys_especialidades
    indexes:
        fk_sys_especialidades_sys_modulos1_idx:
            columns:
                - sys_modulos_id_sys_modulo
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        categoriaSysEspecialidad:
            type: string
            nullable: true
            length: 60
            options:
                fixed: false
            column: categoria_sys_especialidad
        nombreSysEspecialidades:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: nombre_sys_especialidades
        descripcionSysEspecialidades:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: descripcion_sys_especialidades
        codigoSysEspecialidades:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: codigo_sys_especialidades
        esActivoSysEspecialidad:
            type: boolean
            nullable: true
            column: es_activo_sys_especialidad
    manyToOne:
        sysModulosSysModulo:
            targetEntity: SysModulos
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                sys_modulos_id_sys_modulo:
                    referencedColumnName: id_sys_modulo
            orphanRemoval: false
    lifecycleCallbacks: {  }
