AppBundle\Entity\SysHorarios:
    type: entity
    table: sys_horarios
    indexes:
        fk_sys_horarios_sys_usuario1_idx:
            columns:
                - sys_usuario_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        diaSysHorario:
            type: date
            nullable: true
            column: dia_sys_horario
        entradaSysHorario:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
            column: entrada_sys_horario
        salidaSysHorario:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
            column: salida_sys_horario
    manyToOne:
        sysUsuario:
            targetEntity: SysUsuario
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                sys_usuario_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
