AppBundle\Entity\SysInstitucionDetalle:
    type: entity
    table: sys_institucion_detalle
    indexes:
        fk_sys_institucion_detalle_sys_institucion1_idx:
            columns:
                - sys_institucion_id
        fk_sys_institucion_detalle_sys_institucion_propiedad1_idx:
            columns:
                - sys_institucion_propiedad
    id:
        idSysInstitucionDetalle:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_sys_institucion_detalle
            generator:
                strategy: IDENTITY
    fields:
        valorSysInstitucionDetalle:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
            column: valor_sys_institucion_detalle
    manyToOne:
        sysInstitucionPropiedad:
            targetEntity: SysInstitucionPropiedad
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                sys_institucion_propiedad:
                    referencedColumnName: id_sys_institucion_propiedad
            orphanRemoval: false
        sysInstitucion:
            targetEntity: SysInstitucion
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                sys_institucion_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
