AppBundle\Entity\SysLogsAcceso:
    type: entity
    table: sys_logs_acceso
    indexes:
        fk_sys_logs_acceso_sys_usuario1_idx:
            columns:
                - sys_usuario_id
    id:
        idSysLogsAcceso:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_sys_logs_acceso
            generator:
                strategy: IDENTITY
    fields:
        fechaAcceso:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: fecha_acceso
        ipSysLogsAcceso:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: ip_sys_logs_acceso
    manyToOne:
        sysUsuario:
            targetEntity: SysUsuario
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                sys_usuario_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
