AppBundle\Entity\SysModuloTieneEspecialidad:
    type: entity
    table: sys_modulo_tiene_especialidad
    indexes:
        fk_sys_modulo_tiene_especialid_sys_especialidades1_idx:
            columns:
                - sys_especialidades_id
        fk_sys_modulo_tiene_especialid_sys_modulos1_idx:
            columns:
                - sys_modulos_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        sysEstatus:
            type: boolean
            nullable: true
            options:
                default: '1'
            column: sys_estatus
    manyToOne:
        sysEspecialidades:
            targetEntity: SysEspecialidades
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                sys_especialidades_id:
                    referencedColumnName: id
            orphanRemoval: false
        sysModulos:
            targetEntity: SysModulos
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                sys_modulos_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
