AppBundle\Entity\SysMunicipio:
    type: entity
    table: sys_municipio
    indexes:
        fk_sys_minicipio_sys_departamentos1_idx:
            columns:
                - sys_departamentos_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombreSysMunicipo:
            type: string
            nullable: true
            length: 60
            options:
                fixed: false
            column: nombre_sys_municipo
        estatusSysMunicipo:
            type: boolean
            nullable: true
            column: estatus_sys_municipo
        descripcionSysMunicipio:
            type: string
            nullable: true
            length: 60
            options:
                fixed: false
            column: descripcion_sys_municipio
    manyToOne:
        sysDepartamentos:
            targetEntity: SysDepartamentos
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                sys_departamentos_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
