AppBundle\Entity\SysNotificacion:
    type: entity
    table: sys_notificacion
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombreCompleto:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: nombre_completo
        correo:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
        fechaCreacion:
            type: datetime
            nullable: true
            column: fecha_creacion
        estado:
            type: integer
            nullable: true
            options:
                unsigned: false
    lifecycleCallbacks: {  }
