AppBundle\Entity\SysRoles:
    type: entity
    table: sys_roles
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombreRolSysRoles:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
            column: nombre_rol_sys_roles
        estatusSysRoles:
            type: boolean
            nullable: true
            column: estatus_sys_roles
        fechaCreacionSysRoles:
            type: datetime
            nullable: true
            column: fecha_creacion_sys_roles
    lifecycleCallbacks: {  }
