AppBundle\Entity\SysRecetaMedica:
    type: entity
    table: sys_receta_medica
    indexes:
        fk_sys_receta_medica_sys_usuario1_idx:
            columns:
                - sys_usuario_medico
        fk_sys_receta_medica_sys_usuario2_idx:
            columns:
                - sys_usuario_paciente
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombreProductoSysRecetaMedia:
            type: string
            nullable: true
            length: 250
            options:
                fixed: false
            column: nombre_producto_sys_receta_media
        descripcionSysRecetaMedica:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
            column: descripcion_sys_receta_medica
        fechaCreacionRecetaMedica:
            type: date
            nullable: true
            column: fecha_creacion_receta_medica
    manyToOne:
        sysUsuarioMedico:
            targetEntity: SysUsuario
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                sys_usuario_medico:
                    referencedColumnName: id
            orphanRemoval: false
        sysUsuarioPaciente:
            targetEntity: SysUsuario
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                sys_usuario_paciente:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
