AppBundle\Entity\SysUsuarioTieneRol:
    type: entity
    table: sys_usuario_tiene_rol
    indexes:
        fk_sys_usuario_tiene_rol_sys_usuario1_idx:
            columns:
                - sys_usuario_id
        fk_sys_usuario_tiene_rol_sys_roles1_idx:
            columns:
                - sys_roles_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        estadoSysUsuarioTieneRol:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: estado_sys_usuario_tiene_rol
    manyToOne:
        sysRoles:
            targetEntity: SysRoles
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                sys_roles_id:
                    referencedColumnName: id
            orphanRemoval: false
        sysUsuario:
            targetEntity: SysUsuario
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                sys_usuario_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
