AppBundle\Entity\SysUnidadMedida:
    type: entity
    table: sys_unidad_medida
    indexes:
        FK_sys_unidad_medida_sys_categoria_unidad_medida:
            columns:
                - id_categoria_unidad_medida
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombreUnidad:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
                default: '0'
            column: nombre_unidad
        fechaCreacion:
            type: datetime
            nullable: true
            column: fecha_creacion
    manyToOne:
        idCategoriaUnidadMedida:
            targetEntity: SysCategoriaUnidadMedida
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_categoria_unidad_medida:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
