AppBundle\Entity\SysUsuario:
    type: entity
    table: sys_usuario
    indexes:
        FK_sys_usuario_sys_municipio:
            columns:
                - id_municipio_sys_usuario
        FK_sys_usuario_sys_roles:
            columns:
                - id_rol
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombreSysUsuario:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
            column: nombre_sys_usuario
        apellidoSysUsuario:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
            column: apellido_sys_usuario
        emailSysUsuario:
            type: string
            nullable: true
            length: 60
            options:
                fixed: false
            column: email_sys_usuario
        estatusSysUsuario:
            type: boolean
            nullable: true
            column: estatus_sys_usuario
        passwordSysUsuario:
            type: string
            nullable: true
            length: 75
            options:
                fixed: false
            column: password_sys_usuario
        fechaNacimientoSysUsuario:
            type: date
            nullable: true
            column: fecha_nacimiento_sys_usuario
        telefonoSysUsuario:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: telefono_sys_usuario
        celularSysUsuario:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
            column: celular_sys_usuario
        jvrmSysUsuario:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
            column: jvrm_sys_usuario
        tarjetaCreditoSysUsuario:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: tarjeta_credito_sys_usuario
        sysUsuario:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
            column: sys_usuario
        codigoPostalSysUsuario:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: codigo_postal_sys_usuario
        duiSysUsuario:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
            column: dui_sys_usuario
        fechaCreacionSysUsuario:
            type: date
            nullable: true
            column: fecha_creacion_sys_usuario
        fechaActualizacionSysUsuario:
            type: datetime
            nullable: true
            column: fecha_actualizacion_sys_usuario
        genero:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
        ocupacion:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
        direccion:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
        responsableDePaciente:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: responsable_de_paciente
        numeroAfp:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: numero_afp
        numeroNup:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: numero_nup
    manyToOne:
        idMunicipioSysUsuario:
            targetEntity: SysMunicipio
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_municipio_sys_usuario:
                    referencedColumnName: id
            orphanRemoval: false
        idRol:
            targetEntity: SysRoles
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_rol:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
