AppBundle\Entity\SysUsuario:
    type: entity
    table: sys_usuario
    repositoryClass: AppBundle\Repository\SysUsuarioRepository
    indexes:
        FK_sys_roles:
            columns:
                - id_rol
        FK_sys_municipio:
            columns:
                - id_municipio
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        email:
            type: string
            nullable: true
            length: 60
            options:
                fixed: false
        activo:
            type: boolean
            nullable: true
        password:
            type: string
            nullable: true
            length: 40
            options:
                fixed: false
        telefono:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
        tarjetaCredito:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: tarjeta_credito
        usuario:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
            column: usuario
        fechaActualizacion:
            type: datetime
            nullable: true
            column: fecha_actualizacion
        genero:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
        ocupacion:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
        direccion:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
        responsableDePaciente:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: responsable_de_paciente
        numeroAfp:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: numero_afp
        numeroNup:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: numero_nup
        nombre:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
        apellido:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
        fechaNacimiento:
            type: date
            nullable: true
            column: fecha_nacimiento
        celular:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
        jvrm:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
        codigoPostal:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: codigo_postal
        dui:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
        fechaCreacion:
            type: date
            nullable: true
            column: fecha_creacion
    manyToOne:
        idMunicipio:
            targetEntity: SysMunicipio
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_municipio:
                    referencedColumnName: id
            orphanRemoval: false
        idRol:
            targetEntity: SysRoles
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_rol:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
