AppBundle\Entity\SysUsuarioResponsableInstitucion:
    type: entity
    table: sys_usuario_responsable_institucion
    indexes:
        fk_sys_usuario_responsable_institucion_sys_institucion1_idx:
            columns:
                - sys_institucion_id
        fk_sys_usuario_responsable_institucion_sys_usuario1_idx:
            columns:
                - sys_usuario_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    manyToOne:
        sysInstitucion:
            targetEntity: SysInstitucion
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                sys_institucion_id:
                    referencedColumnName: id
            orphanRemoval: false
        sysUsuario:
            targetEntity: SysUsuario
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                sys_usuario_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
