AppBundle\Entity\Timezones:
    type: entity
    table: timezones
    indexes:
        FK_dtim_pais_idx:
            columns:
                - tim_pai_id
    id:
        id:
            type: integer
            id: true
            column: id_timezone
            generator:
                strategy: IDENTITY
    fields:
        timezoneValue:
            type: string
            length: 255
            column: timezone_vlue
        zonaHoraria:
            type: string
            length: 255
            column: zona_horaria
        ciudadTime:
            type: string
            length: 255
            column: timezone_Value
    manyToOne:
        timPai:
            targetEntity: Pais
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                tim_pai_id:
                    referencedColumnName: pai_id
            orphanRemoval: false
    lifecycleCallbacks: {  }
