AppBundle\Entity\Usuario:
    type: entity
    table: usuario
    indexes:
        IDX_usuario:
            columns:
                - usu_usuario
        IDX_2265B05D12023DFD:
            columns:
                - usu_informacion
    id:
        usuId:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            column: usu_id
            generator:
                strategy: IDENTITY
    fields:
        usuUsuario:
            type: string
            nullable: false
            length: 30
            options:
                fixed: false
            column: usu_usuario
        usuClave:
            type: string
            nullable: false
            length: 40
            options:
                fixed: true
            column: usu_clave
        usuFechaRegistro:
            type: datetime
            nullable: false
            column: usu_fecha_registro
        usuIdVendedor:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: usu_id_vendedor
        usuFechaCrea:
            type: datetime
            nullable: true
            column: usu_fecha_crea
        usuFechaMod:
            type: datetime
            nullable: true
            column: usu_fecha_mod
        usuActivo:
            type: boolean
            nullable: false
            options:
                default: '1'
            column: usu_activo
        usuFechaNacimiento:
            type: date
            nullable: true
            column: usu_fecha_nacimiento
        usuTitulo:
            type: string
            nullable: true
            length: 10
            options:
                fixed: false
            column: usu_titulo
        usuGenero:
            type: string
            nullable: false
            length: 1
            options:
                fixed: true
            column: usu_genero
        usuNombre:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: usu_nombre
        usuSegundoNombre:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: usu_segundo_nombre
        usuTercerNombre:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: usu_tercer_nombre
        usuPrimerApellido:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: usu_primer_apellido
        usuSegundoApellido:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: usu_segundo_apellido
        usuCorreo:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: usu_correo
    manyToOne:
        usuInformacion:
            targetEntity: UsuarioInformacion
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                usu_informacion:
                    referencedColumnName: usi_id
            orphanRemoval: false
    lifecycleCallbacks: {  }
