AppBundle\Entity\UsuarioSocial:
    type: entity
    table: usuario_social
    indexes:
        FK__usuario:
            columns:
                - id_usuario
        FK__social_redes:
            columns:
                - id_social_red
    id:
        idUsuSoc:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            column: id_usu_soc
            generator:
                strategy: IDENTITY
    fields:
        usuSocUrl:
            type: string
            nullable: false
            length: 250
            options:
                fixed: false
                default: ''
            column: usu_soc_url
    manyToOne:
        idSocialRed:
            targetEntity: SocialRedes
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_social_red:
                    referencedColumnName: id_soc_red
            orphanRemoval: false
        idUsuario:
            targetEntity: ClienteUsuario
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_usuario:
                    referencedColumnName: cli_usu_id
            orphanRemoval: false
    lifecycleCallbacks: {  }
