AppBundle\Entity\UsuariosRol:
    type: entity
    table: usuarios_rol
    indexes:
        IDX_2E759ED8E73132C6:
            columns:
                - urol_usu_id
        IDX_2E759ED8CAC13B34:
            columns:
                - urol_cli_id
        IDX_2E759ED8723560E8:
            columns:
                - urol_rol_id
    id:
        urolId:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            column: urol_id
            generator:
                strategy: IDENTITY
    manyToOne:
        urolRol:
            targetEntity: Rol
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                urol_rol_id:
                    referencedColumnName: rol_id
            orphanRemoval: false
        urolCli:
            targetEntity: Cliente
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                urol_cli_id:
                    referencedColumnName: cli_id
            orphanRemoval: false
        urolUsu:
            targetEntity: Usuario
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                urol_usu_id:
                    referencedColumnName: usu_id
            orphanRemoval: false
    lifecycleCallbacks: {  }
