AppBundle\Entity\UsuarioInformacion:
    type: entity
    table: usuario_informacion
    id:
        usiId:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            column: usi_id
            generator:
                strategy: IDENTITY
    fields:
        usiDireccion:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: usi_direccion
        usiTelefono:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: usi_telefono
        usiDescripcion:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: usi_descripcion
    lifecycleCallbacks: {  }
