AppBundle\Entity\Usuario:
    type: entity
    repositoryClass: AppBundle\Repository\UsuarioRepository
    table: usuario
    indexes:
        IDX_usuario:
            columns:
                - usu_usuario
    id:
        usuId:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            column: usu_id
            generator:
                strategy: IDENTITY
    fields:
        usuUsuario:
            type: string
            nullable: false
            length: 30
            options:
                fixed: false
            column: usu_usuario
        usuCorreo:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: usu_correo
        usuClave:
            type: string
            nullable: false
            length: 40
            options:
                fixed: true
            column: usu_clave
        usuFechaRegistro:
            type: datetime
            nullable: false
            column: usu_fecha_registro
        usuFechaNacimiento:
            type: date
            nullable: true
            column: usu_fecha_nacimiento
        usuIdVendedor:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: usu_id_vendedor
        usuNombre:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: usu_nombre
        usuTitulo:
            type: string
            nullable: true
            length: 10
            options:
                fixed: false
            column: usu_titulo
        usuGenero:
            type: string
            nullable: false
            length: 1
            options:
                fixed: true
            column: usu_genero
        usuFechaCrea:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
            column: usu_fecha_crea
        usuFechaMod:
            type: datetime
            nullable: true
            column: usu_fecha_mod
        usuActivo:
            type: boolean
            nullable: false
            options:
                default: '1'
            column: usu_activo
        usuFechaNacimiento:
            type: date
            nullable: true
            column: usu_fecha_nacimiento
        usuTitulo:
            type: string
            nullable: true
            length: 10
            options:
                fixed: false
            column: usu_titulo
        usuGenero:
            type: string
            nullable: false
            length: 1
            options:
                fixed: true
            column: usu_genero
    manyToOne:
        usuInformacion:
            targetEntity: UsuarioInformacion
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                usu_informacion:
                    referencedColumnName: usi_id
            orphanRemoval: false
    manyToMany:
        groups:
            targetEntity: Especialidad
            inversedBy: usuarios
            joinTable:
                name: usuarios_especialidad
                joinColumns:
                    uesp_usu_id:
                        referencedColumnName: usu_id
                inverseJoinColumns:
                    uesp_esp_id:
                        referencedColumnName: esp_id
    lifecycleCallbacks: {  }
