AppBundle\Entity\Usuario:
    type: entity
    table: usuario
    indexes:
        IDX_usuario:
            columns:
                - usu_usuario
        usu_activo:
            columns:
                - usu_activo
    id:
        usuId:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            column: usu_id
            generator:
                strategy: IDENTITY
    fields:
        usuUsuario:
            type: string
            nullable: false
            length: 30
            options:
                fixed: false
            column: usu_usuario
        usuClave:
            type: string
            nullable: false
            length: 40
            options:
                fixed: true
            column: usu_clave
        usuGenero:
            type: string
            nullable: false
            length: 1
            options:
                fixed: true
            column: usu_genero
        usuNombre:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: usu_nombre
        usuSegundoNombre:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: usu_segundo_nombre
        usuTercerNombre:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: usu_tercer_nombre
        usuPrimerApellido:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: usu_primer_apellido
        usuSegundoApellido:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: usu_segundo_apellido
    lifecycleCallbacks: {  }
