AppBundle\Entity\UsuarioGaleria:
    type: entity
    table: usuario_galeria
    id:
        galId:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            column: gal_id
            generator:
                strategy: IDENTITY
    fields:
        galHash:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: gal_hash
        galTipo:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
            column: gal_tipo
        galFechaCrea:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
            column: gal_fecha_crea
        galFechaMod:
            type: datetime
            nullable: true
            column: gal_fecha_mod
        galActivo:
            type: boolean
            nullable: false
            options:
                default: '1'
            column: gal_activo
    manyToOne:
        galUsuario:
            targetEntity: Usuario
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                gal_usu_id:
                    referencedColumnName: usu_id
            orphanRemoval: false
        galModulo:
            targetEntity: Modulo
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                gal_modulo_id:
                    referencedColumnName: mod_id
            orphanRemoval: false
        galCliente:
            targetEntity: Cliente
            joinColumn:
                name: gal_cliente_id
                referencedColumnName: cli_id
    lifecycleCallbacks: {  }
