AppBundle\Entity\UsuarioGaleriaTipo:
    type: entity
    table: usuario_galeria_tipo
    id:
        usuGalTipId:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            column: usu_gal_tip_id
            generator:
                strategy: IDENTITY
    fields:
        usuGalTipNombre:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
                default: '0'
            column: usu_gal_tip_nombre
        usuGalTipActivo:
            type: boolean
            nullable: false
            options:
                default: '0'
            column: usu_gal_tip_activo
    lifecycleCallbacks: {  }
