AppBundle\Entity\UsuarioInformacion:
    type: entity
    table: usuario_informacion
    id:
        usiId:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            column: usi_id
            generator:
                strategy: IDENTITY
    fields:
        usiDireccion:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: usi_direccion
        usiTelefono:
            type: string
            nullable: true
            length: 255
            options: 
                fixed: false
            column: usi_telefono
        usiInfoPerfil:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: usi_info_perfil
        usiFb:
            type: string
            nullable: true
            length: 150
            options:
                fixed: false
            column: usi_fb
        usiTwitter:
            type: string
            nullable: true
            length: 150
            options:
                fixed: false
            column: usi_twitter
        usiCorreo:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: usi_correo
        usiDiasTrabajo:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: usi_dias_trabajo
        usiEducacion:
            type: string
            nullable: true
            lenght: 255
            column: usi_educacion
#    oneToMany:
#        infoUsuarios:
#            targetEntity: Usuario
#            mappedBy: usuInformacion
#            fetch: LAZY
#            joinColumns:
#                usi_usu_id:
#                    referencedColumnName: usu_id
#            orphanRemoval: false
    lifecycleCallbacks: {  }
