emr_homepage:
    path:     /
    defaults: { _controller: EmrBundle:Session:login }
    
emr_controller_url_menu_top:
    path:     /module/parameter/{route}
    defaults: { _controller: EmrBundle:Default:redirectMenu }
    host:     "%emr_domain%"

emr_menu_top:
    path:     /menutop
    defaults: { _controller: EmrBundle:MenuTop:listShow  }
    host:     "%emr_domain%"

emr_dashboard:
    path:     /dashboard
    defaults: { _controller: EmrBundle:Dashboard:dashboard  }
    host:     "%emr_domain%"
    
emr_dashboard_appointment:
    path:     /show/appointment
    defaults: { _controller: EmrBundle:Dashboard:showAppointment  }
    host:     "%emr_domain%"
    
emr_location:
    path:     /establecimiento
    defaults: { _controller: EmrBundle:Default:location  }
    host:     "%emr_domain%"
    
emr_checkSessionLocation:
    path:     /revisa/sesion/establecimiento
    defaults: { _controller: EmrBundle:Default:checkSessionLocation  }
    host:     "%emr_domain%"
    
emr_paciente:
    resource: "@EmrBundle/Resources/config/routing/paciente.yml"
    prefix:   /paciente
    host:     "%emr_domain%"
    
emr_perfil:
    resource: "@EmrBundle/Resources/config/routing/perfil.yml"
    prefix:   /perfil
    host:     "%emr_domain%"
    
emr_checkImageProfile:
    path:     /photo/user/profile
    defaults: { _controller: EmrBundle:Default:getThubmanlImageProfileAction  }
    host:     "%emr_domain%" 

emr_messages:
    path:     /messages
    defaults: { _controller: EmrBundle:Default:getAllMessagesAction  }
    host:     "%emr_domain%"
    
emr_message_detail:
    path:     /getmessage
    defaults: { _controller: EmrBundle:Default:getDetailMessage  }
    host:     "%emr_domain%"


emr_invarea:
    resource: "@EmrBundle/Resources/config/routing/invarea.yml"
    prefix:   /invarea
    host:     "%emr_domain%"

app_invcategoria:
    resource: "@EmrBundle/Resources/config/routing/invcategoria.yml"
    prefix:   /invcategoria
    host:     "%emr_domain%"
    
emr_location_per_country:
    path:     /state/municipality
    defaults: { _controller: "EmrBundle:Paciente:getStatesFromCountry" }        
    
emr_cliente:
    resource: "@EmrBundle/Resources/config/routing/cliente.yml"
    prefix:   /cliente

emr_invunidadmedida:
    resource: "@EmrBundle/Resources/config/routing/invunidadmedida.yml"
    prefix:   /invunidadmedida
    host:     "%emr_domain%"

emr_invgrupo:
    resource: "@EmrBundle/Resources/config/routing/invgrupo.yml"
    prefix:   /invgrupo
    host:     "%emr_domain%"

emr_invmovimiento:
    resource: "@EmrBundle/Resources/config/routing/invmovimiento.yml"
    prefix:   /invmovimiento
    host:     "%emr_domain%"

emr_invmovimientodetalle:
    resource: "@EmrBundle/Resources/config/routing/invmovimientodetalle.yml"
    prefix:   /invmovimientodetalle
    host:     "%emr_domain%"

emr_invproveedor:
    resource: "@EmrBundle/Resources/config/routing/invproveedor.yml"
    prefix:   /invproveedor
    host:     "%emr_domain%"

emr_invtipomovimiento:
    resource: "@EmrBundle/Resources/config/routing/invtipomovimiento.yml"
    prefix:   /invtipomovimiento
    host:     "%emr_domain%"

app_invtipopresentacion:
    resource: "@EmrBundle/Resources/config/routing/invtipopresentacion.yml"
    prefix:   /invtipopresentacion
    host:     "%emr_domain%"

app_invtipoproveedor:
    resource: "@EmrBundle/Resources/config/routing/invtipoproveedor.yml"
    prefix:   /invtipoproveedor
    host:     "%emr_domain%"

emr_inventario:
    resource: "@EmrBundle/Resources/config/routing/inventario.yml"
    prefix:   /inventario
    host:     "%emr_domain%"
    
#agenda
emr_agenda:
    resource: "@EmrBundle/Resources/config/routing/agenda.yml"
    prefix:   /agenda
    host:     "%emr_domain%"

#consulta médica    
emr_consulta:
    resource: "@EmrBundle/Resources/config/routing/consulta.yml"
    prefix:   /consulta
    host:     "%emr_domain%"
    
#eav    
emr_eav:
    resource: "@EmrBundle/Resources/config/routing/eav.yml"
    prefix:   /eav
    host:     "%emr_domain%"
    
emr_ajustes_sistema:
    resource: "@EmrBundle/Resources/config/routing/ajustes.yml"
    prefix:   /ajustes
    host:     "%emr_domain%"