emr_homepage:
    path:     /
    defaults: { _controller: EmrBundle:Session:login }
    
emr_controller_url_menu_top:
    path:     /module/parameter/{route}
    defaults: { _controller: EmrBundle:Default:redirectMenu }
    host:     "%emr_domain%"

emr_menu_top:
    path:     /menutop
    defaults: { _controller: EmrBundle:MenuTop:listShow  }
    host:     "%emr_domain%"

emr_dashboard:
    path:     /dashboard
    defaults: { _controller: EmrBundle:Dashboard:dashboard  }
    host:     "%emr_domain%"
    
emr_paciente:
    resource: "@EmrBundle/Resources/config/routing/paciente.yml"
    prefix:   /paciente
    host:     "%emr_domain%"


app_invarea:
    resource: "@EmrBundle/Resources/config/routing/invarea.yml"
    prefix:   /invarea
    host:     "%emr_domain%"

app_invcategoria:
    resource: "@EmrBundle/Resources/config/routing/invcategoria.yml"
    prefix:   /invcategoria
    host:     "%emr_domain%"
    

emr_location_per_country:
    path:     /state/municipality
    defaults: { _controller: "EmrBundle:Paciente:getStatesFromCountry" }        
    
emr_cliente:
    resource: "@EmrBundle/Resources/config/routing/cliente.yml"
    prefix:   /cliente
