web_demo:
    path:     /getDoctor
    defaults: { _controller: WebBundle:Default:getDoctor }

web_getDoctorByName:
    path:     /getDoctorByName
    defaults: { _controller: WebBundle:Default:getDoctorByName }    

web_getEspecialidadById:
    path:     /getEspecialidadById
    defaults: { _controller: WebBundle:Default:getEspecialidadById } 

web_especialidad:
    path:     /getAllEspecialidad
    defaults: { _controller: WebBundle:Default:getAllEspecialidad } 

web_getClienteById:
    path:     /getClienteById
    defaults: { _controller: WebBundle:Default:getClienteById }     

web_homepage:
    path:     /
    defaults: { _controller: WebBundle:Default:index }

web_doctores:
    path:     /doctores
    defaults: { _controller: WebBundle:Default:indexDoctores }
    
web_doctores_perfil:
    path:     /doctores/perfil/{med_id}/{texto}
    defaults: { _controller: WebBundle:Default:indexProfile, med_id : null, texto: ""}

web_hospitales:
    path:     /hospitales
    defaults: { _controller: WebBundle:Default:indexHospitales }

web_farmacias:
    path:     /farmacias
    defaults: { _controller: WebBundle:Default:indexFarmacias }

web_precios:
    path:     /precios
    defaults: { _controller: WebBundle:Default:indexPrecios }

web_terminos:
    path:     /terminos
    defaults: { _controller: WebBundle:Default:indexTerminos }

web_privacidad:
    path:     /privacidad
    defaults: { _controller: WebBundle:Default:indexPrivacidad }

web_solicitar_cita:
    path:   /solicitar
    defaults: { _controller: WebBundle:Default:indexSolicitar }

web_contactanos:
    path:     /contactanos
    defaults: { _controller: WebBundle:Default:indexContactanos }

web_solicitar_contacto:
    path:     /solicitar2
    defaults: { _controller: WebBundle:Default:indexContactos }
