web_homepage:
    path:     /
    defaults: { _controller: WebBundle:Default:index }

web_doctores:
    path:     /doctores
    defaults: { _controller: WebBundle:Default:indexDoctores }
    
web_doctores_perfil:
    path:     /doctores/perfil/{med_id}
    defaults: { _controller: WebBundle:Default:indexProfile, med_id : null}

web_hospitales:
    path:     /hospitales
    defaults: { _controller: WebBundle:Default:indexHospitales }

web_farmacias:
    path:     /farmacias
    defaults: { _controller: WebBundle:Default:indexFarmacias }

web_precios:
    path:     /precios
    defaults: { _controller: WebBundle:Default:indexPrecios }

web_terminos:
    path:     /terminos
    defaults: { _controller: WebBundle:Default:indexTerminos }

web_solicitar_cita:
    path:   /solicitar
    defaults: { _controller: WebBundle:Default:indexSolicitar }

web_contactanos:
    path:     /contactanos
    defaults: { _controller: WebBundle:Default:indexContactanos }

web_solicitar_contacto:
    path:     /solicitar2
    defaults: { _controller: WebBundle:Default:indexContactos }
